### ISSUE TITLE
Block 07 Checklist

### ISSUE THREAD

**Issue by JoshuaDevine** [JoshuaDevine/Residency#2]
## Faculty

- [ ] Faculty PTO
- [ ] Preceptor Coverage
    - [ ] Procedures
    - [ ] Colpo

## Rotations

- [ ] Ambulatory Care
    >`Tuesday AM - Neuro | Clinic`
- [ ] Peds & Peds Teen
    >`Input template data into AMION`
- [ ] HIV
    >`Tuesday/Thursday Clinic all day based on needs`
- [ ] Urgent Care
    >`Tuesday/Thursday Clinic all day based on needs`
- [ ] Sports Med
    >`Block PM template to allow for travel`
    - [ ] Block any applicable procedures clinics
- [ ] Electives

## Clinic Assignments

- [ ] Nursing Home
- [ ] HIV/SPNS Track
- [ ] Chief Admin `Lee`
- [ ] Chief Admin `Wang`
- [ ] BHC Clinic
- [ ] Procedures
- [ ] Colpo
- [ ] Group Classes
    - [ ] `Healthy Living`
    - [ ] `DMCCP/DGV`

## Reminders

- [ ] Colpo  `WCM`  
- [ ] Nursing Home `Dr. Reznik`
- [ ] SPNS  `Lorenzo`
- [ ] Shadow
    - [ ] `Providers`
    - [ ] `CH Admin`
- [ ] Senior/Lone Wolf switches in BL07.

## Events

- [ ] Holidays
- [ ] Interviews
- [ ] Retreat
- [ ] Graduation
- [ ] Conferences

**Comment by JoshuaDevine** [comment]
# Test

**Comment by JoshuaDevine** [comment]
#3
